spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.92.115.93:3306/sleep?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: ADmin123?
# 打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9090
